apiVersion: v1
kind: Service
metadata:
  namespace: kari-ss-REPLACE_SS_VERSION-ns
  name: kari-ss-REPLACE_SS_VERSION-deployment-lb
  labels:
    component: kari-ss-REPLACE_SS_VERSION-component
    role: kari-ss-REPLACE_SS_VERSION-role
  # For AWS EKS, not tested if messes with Azure AKS deployment.
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    component: kari-ss-REPLACE_SS_VERSION-component
    role: kari-ss-REPLACE_SS_VERSION-role
  REPLACE_SS_IP
  ports:
  - name: http
    port: 3045
    nodePort: REPLACE_SS_NODEPORT
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kari-ss-REPLACE_SS_VERSION-ns
  name: kari-ss-REPLACE_SS_VERSION-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kari-ss-REPLACE_SS_VERSION-component
      role: kari-ss-REPLACE_SS_VERSION-role
  template:
    metadata:
      labels:
        component: kari-ss-REPLACE_SS_VERSION-component
        role: kari-ss-REPLACE_SS_VERSION-role
    spec:
      containers:
      - name: kari-ss-REPLACE_SS_VERSION-component
        image: REPLACE_SS_IMAGE_TAG
        env:
        - name: SS_ENV
          value: REPLACE_SS_ENV_VERSION
        - name: MY_ENV
          value: dev
          # AWS endpoint, hard coded for the exercise.
        - name: ENDPOINT
          value: eu-west-1
          # AWS table prefix, hard coded for the exercise.
        - name: SS_TABLE_PREFIX
          value: kari-sseks
        - name: AZURE_CONNECTION_STRING
          value: REPLACE_SS_ENDPOINT
        ports:
        - containerPort: 3045
          name: http
          protocol: TCP
